spring.application.name=back
# Firebase Database URL 
firebase.database.url=https://kwiyeh-26c18-default-rtdb.europe-west1.firebasedatabase.app/
# Path to your service account JSON file
firebase.config.path=classpath:E://kwiyeh//back//src//main//resources//firebase//serviceAccountKey.json
# Exclude DataSource Auto-Configuration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

firebase.api.key=AIzaSyAa7ktXpOkuvnSozAlZYHfdxXjZ_bpvBoc