spring.application.name=back
# Firebase Database URL
firebase.database.url=https://kwiyeh-26c18-default-rtdb.europe-west1.firebasedatabase.app/
# Exclude DataSource Auto-Configuration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

firebase.api.key=AIzaSyAa7ktXpOkuvnSozAlZYHfdxXjZ_bpvBoc
#enable Starttls for secure mail sending
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ttemtsa@gmail.com
spring.mail.password=xnfa pgav xbsc brvh
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.required=true


 spring.mvc.dispatch-options-request=true